Title: Preliminary Survey Data Onboarding
Author: CC
Image: https://www.designtagebuch.de/wp-content/uploads/mediathek//2018/01/bayer-logo-1100x825.jpg
Theme: 282828




Questions:
    Question1:
        Type: ShortText
        Label: Please enter your name (first name, last name)
    Question2:
        Type: ShortText
        Label: Please enter your email address
    Question3:
        Type: ShortText
        Label: Please enter your CWID
    Question4:
        Type: ShortText
        Label: Please enter your affiliation (eg. Supervisor, Team, Technical Contact, SNOW Assignment)
    Question5:
        Type: Radio
        Label: Are logs being sent to Splunk currently?
        Values:
            Value1: Yes
            Value2: No



    Question6:
        Type: CheckBox
        Label: Topic of your Splunk Ticket:
          Values:
            Value1: New Data to be onboarded to Splunk
            Value2: Existing Data to be reconfigured
            Value3: Existing Data to be offboarded from Splunk
            Value4: Enhancing Splunk Services for our Use Case


    Question7:
        Type: Radio
        Label: Do You Need Personal Assistance from Splunk Support?
        Values:
            Value1: I Don't Need Additional Support.
            Value2: Please Set up a Meeting to Discuss Procedure.


    Question8:
        Type: Radio
        Label: Do you have Access to Remedy/Snow/other Asset Mngmt?
        Values:
            Value1: Yes
            Value2: No
            Value3: Yes (Workorder Already Exists)
            Value4: Can't specify

    Question9:
        Type: ShortText
        Label: If Workorder exists, please provide Incident Number

    Question10:
        Type: Radio
        Label: Is the data flagged as security relevant?
        Values:
            Value1: Yes
            Value2: No
